### ISSUE TITLE
Getting hit on a ledge cancels damage knockback

### ISSUE THREAD

**Issue by NovalChalice** [GalaxyTrail/GFR_bugs#29] opened 2018-01-09 02:18 UTC
As the title explains, if Rena is standing on a ledge and is damaged by an enemy, The ledge will cancel the damage knockback and Rena will bounce in the same spot she was standing. This issue is not present on any other terrain.

**Comment by NovalChalice** [comment] 2018-01-09 02:25
![screenshot_855](https://user-images.githubusercontent.com/25521094/34702202-694cd8c4-f4ba-11e7-8f18-716c87c6fb98.png)

The bug can happen in a situation such as this

**Comment by NovalChalice** [comment] 2018-01-09 02:51
Video for the bug
https://youtu.be/9bgdO1_SfGI

**Comment by FlutterSprite** [comment] 2018-01-09 02:53
Working as intended, but if it feels like a bug, this should be adjusted - thank you!

**Comment by FlutterSprite** [comment] 2018-12-05 02:01
Deciding to close this one for now!

**Closed as completed by FlutterSprite** 2018-12-05 02:01 UTC
Labels: enhancement
